### ISSUE TITLE
VAlue error: appears like randomint is getting high value=0

### ISSUE THREAD

**Issue by n7377747** [habom2310/face-recognition-with-keras-and-dlib#2]
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    len(ids))]].reshape(-1), train_embs[idx].reshape(-1)))
  File "mtrand.pyx", line 628, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1321, in numpy.random.bounded_integers._rand_int32
ValueError: low >= high

**Comment by n7377747** [comment]
line 129 from the code given
